# Generated by Django 5.2.4 on 2025-07-26 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customuser',
            old_name='resistration_code',
            new_name='registration_code',
        ),
    ]
